import type { CairnAPI } from "@cairn/shared";
import { bustCacheForTests } from "./cache.js";
import { resetViewModeForTests } from "./viewMode.js";

export function defaultCairn(): CairnAPI {
  return {
    getConfig: async () => ({ ok: true, data: undefined }),
    setConfig: async () => ({ ok: true, data: undefined }),
    overviewSummary: async () => ({
      ok: true,
      data: {
        providersConnected: 0,
        accountsTotal: 0,
        accountsEnabled: 0,
        appsDetected: 0,
        pluginsInstalled: 0,
        providerHealth: [],
        serverRunning: false,
        serverPort: 34567,
      },
    }),
    accountsList: async () => ({ ok: true, data: [] }),
    accountsEnable: async () => ({ ok: true, data: undefined }),
    accountsRemove: async () => ({ ok: true, data: undefined }),
    accountsRefreshQuota: async () => ({ ok: true, data: [] }),
    accountsLoginBegin: async () => ({ ok: true, data: { url: "https://example/login", instructions: "" } }),
    accountsLoginComplete: async () => ({ ok: true, data: { added: true } }),
    accountsLoginCancel: async () => ({ ok: true, data: undefined }),
    providersList: async () => ({ ok: true, data: [] }),
    providersSetEnabled: async () => ({ ok: true, data: undefined }),
    providersSetExposure: async () => ({ ok: true, data: undefined }),
    routingApps: async () => ({ ok: true, data: [] }),
    routingGet: async () => ({ ok: true, data: { tiers: [], map: { default: [] }, catalog: [] } }),
    routingSetChain: async () => ({ ok: true, data: { warnings: [] } }),
    proxyStatus: async () => ({ ok: true, data: { running: false, port: 34567 } }),
    proxyStart: async () => ({ ok: true, data: undefined }),
    proxyStop: async () => ({ ok: true, data: undefined }),
    proxiesList: async () => ({ ok: true, data: [] }),
    proxiesSetEnabled: async () => ({ ok: true, data: undefined }),
    appsDetect: async () => ({ ok: true, data: { claude: false, opencode: false } }),
    appsList: async () => ({
      ok: true,
      data: [
        { id: "claude", label: "Claude Code" },
        { id: "opencode", label: "OpenCode" },
      ],
    }),
    jobsList: async () => ({ ok: true, data: [] }),
    jobsEnqueue: async () => ({ ok: false, error: "no job runner in tests" }),
    jobsCancel: async () => ({ ok: true, data: false }),
    jobsClearFinished: async () => ({ ok: true, data: undefined }),
    onJobEvent: () => () => {},
    appsInstallCli: async () => ({ ok: true, data: { stdout: "", stderr: "" } }),
    appsUninstallCli: async () => ({ ok: true, data: { stdout: "", stderr: "" } }),
    appsSummary: async () => ({
      ok: true,
      data: {
        accounts: [],
        providerCount: 0,
        accountsEnabled: 0,
        providerBreakdown: [],
        quotaMinPct: null,
        configDir: "",
        pluginCount: 0,
        routingSlots: null,
      },
    }),
    appsConnection: async () => ({ ok: true, data: { app: "", cliPresent: false, loaderId: null, loaderUrl: null, loaderInstalled: false } }),
    appsInstallLoader: async () => ({ ok: true, data: undefined }),
    appStorageGet: async (app: string) => ({ ok: true, data: { app, home: "/home/app", names: { repos: "repos", plugin: "plugin", cache: "cache", config: "config" }, defaults: { repos: "repos", plugin: "plugin", cache: "cache", config: "config" }, resolved: { repos: "/home/app/repos", plugin: "/home/app/plugin", cache: "/home/app/cache", config: "/home/app/config" } } }),
    appStorageSet: async (_app: string, names: never) => ({ ok: true, data: { names, moves: [] } }),
    repoMeta: async () => ({ ok: true, data: { owner: "", repo: "", htmlUrl: "", stars: null, description: "", topics: [], readme: null } }),
    repoMetaCached: async () => ({ ok: true, data: null }),
    pluginsList: async () => ({ ok: true, data: [] }),
    pluginsListCached: async () => ({ ok: true, data: [] }),
    librariesList: async () => ({ ok: true, data: [] }),
    pluginVersions: async () => ({ ok: true, data: {} }),
    pluginVersionsAll: async () => ({ ok: true, data: {} }),
    pluginVersionsCached: async () => ({ ok: true, data: {} }),
    settingsSections: async () => ({ ok: true, data: [] }),
    enginesList: async () => ({ ok: true, data: [] }),
    enginesEnsure: async () => ({ ok: true, data: undefined }),
    pluginsInstall: async (_home, _name, _url) => ({ ok: true, data: undefined }),
    pluginsRemoveEverywhere: async (_name) => ({ ok: true, data: { outcomes: [] } }),
    pluginsSetEnabled: async (_home, _name, _on) => ({ ok: true, data: undefined }),
    pluginsSetAutoUpdate: async (_home, _name, _on) => ({ ok: true, data: undefined }),
    pluginsSetChannel: async () => ({ ok: true, data: undefined }),
    pluginsDowngrade: async (_home, _name, _hash) => ({ ok: true, data: undefined }),
    pluginsUninstall: async (_home, _name) => ({ ok: true, data: undefined }),
    pluginsData: async () => ({ ok: true, data: [] }),
    pluginsRemoveData: async () => ({ ok: true, data: [] }),
    configSchemas: async () => ({ ok: true, data: [] }),
    configWrite: async (_home, _plugin, _key, _value) => ({ ok: true, data: undefined }),
    configAction: async (_home, _plugin, _actionId) => ({ ok: true, data: { stdout: "", stderr: "" } }),
    screensList: async () => ({ ok: true, data: [] }),
    screenData: async () => ({ ok: true, data: { sources: {} } }),
    screenInvoke: async () => ({ ok: true, data: { ok: true } }),
    busDrain: async () => ({ ok: true, data: [] }),
    activityRead: async () => ({ ok: true, data: { records: [] } }),
    activityStats: async () => ({ ok: true, data: { homes: [], bytes: 0, segments: 0 } }),
    updatesCheck: async () => ({ ok: true, data: { checkedAt: new Date(0).toISOString(), available: [] } }),
    updatesOne: async () => ({ ok: true, data: { updated: [], skipped: [], failed: [], checkedAt: new Date(0).toISOString() } }),
    updatesAll: async () => ({ ok: true, data: { updated: [], skipped: [], failed: [], checkedAt: new Date(0).toISOString() } }),
    globalSettingsRead: async () => ({ ok: true, data: { defaults: {}, fields: [], current: {} } }),
    usageSnapshot: async () => ({ ok: true, data: { accounts: [], sessions: [], models: {}, updatedAt: "" } }),
    importApps: async () => ({ ok: true, data: [] }),
    importPreview: async () => ({ ok: true, data: { accounts: 0, routingSlots: null, exposedProviders: 0 } }),
    importRun: async () => ({ ok: true, data: { accounts: 0, providers: 0, routingImported: false, notes: [] } }),
    catalogList: async () => ({ ok: true, data: { entries: [], source: "anonymous", org: "intisy-ai", rateLimited: false, sources: [] } }),
    librariesRemove: async () => ({ ok: true, data: undefined }),
    marketplaceSourcesList: async () => ({ ok: true, data: [] }),
    marketplaceSourcesSave: async (sources) => ({ ok: true, data: sources }),
    catalogListCached: async () => ({ ok: true, data: null }),
    githubStatus: async () => ({
      ok: true,
      data: { source: "anonymous", connected: false, login: null, name: null, avatarUrl: null, ghCliDetected: false, ghCli: null, accounts: [], activeLogin: null, cairnRepoUrl: "https://github.com/intisy-ai/cairn", cairnStarred: null },
    }),
    githubAddAccount: async (_token: string, _star: boolean) => ({ ok: true, data: { login: "octocat" } }),
    githubSwitchAccount: async () => ({ ok: true, data: undefined }),
    githubRemoveAccount: async () => ({ ok: true, data: undefined }),
    githubConnectGhCli: async (_star: boolean) => ({ ok: true, data: { login: "octocat" } }),
    githubSetStar: async (_url: string, _starred: boolean) => ({ ok: true, data: undefined }),
    githubStarCairn: async () => ({ ok: true, data: undefined }),
    githubDeviceStart: async () => ({ ok: true, data: { userCode: "ABCD-1234", verificationUri: "https://github.com/login/device", intervalSeconds: 5 } }),
    githubDevicePoll: async (_star: boolean) => ({ ok: true, data: { status: "authorized", login: "octocat" } }),
    favoritesList: async () => ({ ok: true, data: [] }),
    favoritesToggle: async (_name: string) => ({ ok: true, data: [] }),
    customEndpointsList: async () => ({ ok: true, data: [] }),
    customEndpointsFormats: async () => ({ ok: true, data: ["openai"] }),
    customEndpointsUpsert: async () => ({ ok: true, data: undefined }),
    customEndpointsRemove: async () => ({ ok: true, data: undefined }),
    customEndpointsSaveKey: async () => ({ ok: true, data: undefined }),
    pluginLedger: async () => ({ ok: true, data: [] }),
    pluginQuarantine: async () => ({ ok: true, data: [] }),
    minimize: () => {},
    maximize: () => {},
    close: () => {},
    onServerStatus: () => () => {},
    onDownloadProgress: () => () => {},
    onActivityEvent: () => () => {},
    isElectron: true,
    platform: "linux",
  };
}

export function stubCairn(overrides: Partial<CairnAPI> = {}): void {
  bustCacheForTests();
  resetViewModeForTests();
  (globalThis as { window: Window }).window.cairn = { ...defaultCairn(), ...overrides };
}
