import type { CairnAPI } from "@cairn/shared";
import { bustCacheForTests } from "./cache.js";

function defaultCairn(): CairnAPI {
  return {
    getConfig: async () => ({ ok: true, data: undefined }),
    setConfig: async () => ({ ok: true, data: undefined }),
    overviewSummary: async () => ({
      ok: true,
      data: {
        providersConnected: 0,
        accountsTotal: 0,
        accountsEnabled: 0,
        appsDetected: 0,
        pluginsInstalled: 0,
        providerHealth: [],
        serverRunning: false,
        serverPort: 34567,
      },
    }),
    accountsList: async () => ({ ok: true, data: [] }),
    accountsEnable: async () => ({ ok: true, data: undefined }),
    accountsRemove: async () => ({ ok: true, data: undefined }),
    accountsRefreshQuota: async () => ({ ok: true, data: [] }),
    accountsLoginBegin: async () => ({ ok: true, data: { url: "https://example/login", instructions: "" } }),
    accountsLoginComplete: async () => ({ ok: true, data: { added: true } }),
    accountsLoginCancel: async () => ({ ok: true, data: undefined }),
    providersList: async () => ({ ok: true, data: [] }),
    providersSetActive: async () => ({ ok: true, data: undefined }),
    providersSetExposure: async () => ({ ok: true, data: undefined }),
    routingApps: async () => ({ ok: true, data: [] }),
    routingGet: async () => ({ ok: true, data: { tiers: [], map: { default: [] }, catalog: [] } }),
    routingSetChain: async () => ({ ok: true, data: { warnings: [] } }),
    proxyStatus: async () => ({ ok: true, data: { running: false, port: 34567 } }),
    proxyStart: async () => ({ ok: true, data: undefined }),
    proxyStop: async () => ({ ok: true, data: undefined }),
    proxiesList: async () => ({ ok: true, data: [] }),
    proxiesSetEnabled: async () => ({ ok: true, data: undefined }),
    appsDetect: async () => ({ ok: true, data: { claude: false, opencode: false } }),
    appsList: async () => ({
      ok: true,
      data: [
        { id: "claude", label: "Claude Code" },
        { id: "opencode", label: "OpenCode" },
      ],
    }),
    appsInstallCli: async () => ({ ok: true, data: { stdout: "", stderr: "" } }),
    appsInit: async () => ({ ok: true, data: { stdout: "", stderr: "" } }),
    appsUninstallCli: async () => ({ ok: true, data: { stdout: "", stderr: "" } }),
    appsSummary: async () => ({
      ok: true,
      data: {
        accounts: [],
        providerCount: 0,
        accountsEnabled: 0,
        providerBreakdown: [],
        quotaMinPct: null,
        configDir: "",
        pluginCount: 0,
        routingSlots: null,
      },
    }),
    appsConnection: async () => ({ ok: true, data: { app: "", cliPresent: false, loaderId: null, loaderUrl: null, loaderInstalled: false } }),
    appsInstallLoader: async () => ({ ok: true, data: undefined }),
    repoMeta: async () => ({ ok: true, data: { owner: "", repo: "", htmlUrl: "", stars: null, description: "", topics: [], readme: null } }),
    repoMetaCached: async () => ({ ok: true, data: null }),
    pluginsList: async () => ({ ok: true, data: [] }),
    pluginVersions: async () => ({ ok: true, data: {} }),
    pluginVersionsAll: async () => ({ ok: true, data: {} }),
    pluginVersionsCached: async () => ({ ok: true, data: {} }),
    enginesList: async () => ({ ok: true, data: [] }),
    enginesEnsure: async () => ({ ok: true, data: undefined }),
    pluginsInstall: async (_home, _name, _url) => ({ ok: true, data: undefined }),
    pluginsInstallMany: async (_name, _url, _homeIds) => ({ ok: true, data: { outcomes: [] } }),
    pluginsRemoveEverywhere: async (_name) => ({ ok: true, data: { outcomes: [] } }),
    pluginsSetEnabled: async (_home, _name, _on) => ({ ok: true, data: undefined }),
    pluginsSetAutoUpdate: async (_home, _name, _on) => ({ ok: true, data: undefined }),
    pluginsDowngrade: async (_home, _name, _hash) => ({ ok: true, data: undefined }),
    pluginsUninstall: async (_home, _name) => ({ ok: true, data: undefined }),
    configSchemas: async () => ({ ok: true, data: [] }),
    configWrite: async (_home, _plugin, _key, _value) => ({ ok: true, data: undefined }),
    configAction: async (_home, _plugin, _actionId) => ({ ok: true, data: { stdout: "", stderr: "" } }),
    syncStatus: async () => ({ ok: true, data: { enabled: true, categories: { accounts: true, plugins: true, settings: true, pluginConfigs: true }, exclude: [], homes: [], pluginConfigs: [] } }),
    syncRun: async () => ({ ok: true, data: undefined }),
    syncSetConfig: async () => ({ ok: true, data: undefined }),
    ledgerHomes: async () => ({ ok: true, data: [] }),
    ledgerCommit: async () => ({ ok: true, data: true }),
    ledgerRestore: async () => ({ ok: true, data: 0 }),
    ledgerDiffRefs: async () => ({ ok: true, data: [] }),
    ledgerProfileCreate: async () => ({ ok: true, data: undefined }),
    ledgerProfileSwitch: async () => ({ ok: true, data: { ok: true } }),
    busDrain: async () => ({ ok: true, data: [] }),
    usageSnapshot: async () => ({ ok: true, data: { accounts: [], sessions: [], models: {}, updatedAt: "" } }),
    importApps: async () => ({ ok: true, data: [] }),
    importPreview: async () => ({ ok: true, data: { accounts: 0, routingSlots: null, exposedProviders: 0 } }),
    importRun: async () => ({ ok: true, data: { accounts: 0, providers: 0, routingImported: false, notes: [] } }),
    catalogList: async () => ({ ok: true, data: { entries: [], source: "anonymous", org: "intisy-ai" } }),
    githubStatus: async () => ({
      ok: true,
      data: { source: "anonymous", connected: false, login: null, name: null, avatarUrl: null, ghCliDetected: false, ghCli: null, accounts: [], activeLogin: null },
    }),
    githubAddAccount: async (_token: string, _star: boolean) => ({ ok: true, data: { login: "octocat" } }),
    githubSwitchAccount: async () => ({ ok: true, data: undefined }),
    githubRemoveAccount: async () => ({ ok: true, data: undefined }),
    githubConnectGhCli: async (_star: boolean) => ({ ok: true, data: { login: "octocat" } }),
    githubSetStar: async (_url: string, _starred: boolean) => ({ ok: true, data: undefined }),
    favoritesList: async () => ({ ok: true, data: [] }),
    favoritesToggle: async (_name: string) => ({ ok: true, data: [] }),
    customEndpointsList: async () => ({ ok: true, data: [] }),
    customEndpointsUpsert: async () => ({ ok: true, data: undefined }),
    customEndpointsRemove: async () => ({ ok: true, data: undefined }),
    customEndpointsSaveKey: async () => ({ ok: true, data: undefined }),
    minimize: () => {},
    maximize: () => {},
    close: () => {},
    onServerStatus: () => () => {},
    onDownloadProgress: () => () => {},
    isElectron: true,
    platform: "linux",
  };
}

export function stubCairn(overrides: Partial<CairnAPI> = {}): void {
  bustCacheForTests();
  (globalThis as { window: Window }).window.cairn = { ...defaultCairn(), ...overrides };
}
