import type { CairnAPI } from "@cairn/shared";

function defaultCairn(): CairnAPI {
  return {
    getConfig: async () => ({ ok: true, data: undefined }),
    setConfig: async () => ({ ok: true, data: undefined }),
    overviewSummary: async () => ({
      ok: true,
      data: {
        providersConnected: 0,
        accountsTotal: 0,
        accountsEnabled: 0,
        appsDetected: 0,
        pluginsInstalled: 0,
        providerHealth: [],
        serverRunning: false,
        serverPort: 34567,
      },
    }),
    accountsList: async () => ({ ok: true, data: [] }),
    accountsEnable: async () => ({ ok: true, data: undefined }),
    accountsRemove: async () => ({ ok: true, data: undefined }),
    accountsRefreshQuota: async () => ({ ok: true, data: [] }),
    providersList: async () => ({ ok: true, data: [] }),
    providersSetActive: async () => ({ ok: true, data: undefined }),
    providersSetExposure: async () => ({ ok: true, data: undefined }),
    routingApps: async () => ({ ok: true, data: [] }),
    routingGet: async () => ({ ok: true, data: { tiers: [], map: { default: [] }, catalog: [] } }),
    routingSetChain: async () => ({ ok: true, data: { warnings: [] } }),
    proxyStatus: async () => ({ ok: true, data: { running: false, port: 34567 } }),
    proxyStart: async () => ({ ok: true, data: undefined }),
    proxyStop: async () => ({ ok: true, data: undefined }),
    appsDetect: async () => ({ ok: true, data: { claude: false, opencode: false } }),
    appsList: async () => ({
      ok: true,
      data: [
        { id: "claude", label: "Claude Code" },
        { id: "opencode", label: "OpenCode" },
      ],
    }),
    appsInstallCli: async () => ({ ok: true, data: { stdout: "", stderr: "" } }),
    appsInit: async () => ({ ok: true, data: { stdout: "", stderr: "" } }),
    appsUninstallCli: async () => ({ ok: true, data: { stdout: "", stderr: "" } }),
    appsSummary: async () => ({
      ok: true,
      data: {
        accounts: [],
        providerCount: 0,
        accountsEnabled: 0,
        providerBreakdown: [],
        quotaMinPct: null,
        configDir: "",
        pluginCount: 0,
        routingSlots: null,
      },
    }),
    pluginsList: async () => ({ ok: true, data: [] }),
    pluginsInstall: async (_home, _name, _url) => ({ ok: true, data: undefined }),
    pluginsInstallMany: async (_name, _url, _homeIds) => ({ ok: true, data: { outcomes: [] } }),
    pluginsRemoveEverywhere: async (_name) => ({ ok: true, data: { outcomes: [] } }),
    pluginsSetEnabled: async (_home, _name, _on) => ({ ok: true, data: undefined }),
    pluginsDowngrade: async (_home, _name, _hash) => ({ ok: true, data: undefined }),
    pluginsUninstall: async (_home, _name) => ({ ok: true, data: undefined }),
    configSchemas: async () => ({ ok: true, data: [] }),
    configWrite: async (_home, _plugin, _key, _value) => ({ ok: true, data: undefined }),
    usageSnapshot: async () => ({ ok: true, data: { accounts: [], sessions: [], models: {}, updatedAt: "" } }),
    importApps: async () => ({ ok: true, data: [] }),
    importPreview: async () => ({ ok: true, data: { accounts: 0, routingSlots: null, exposedProviders: 0 } }),
    importRun: async () => ({ ok: true, data: { accounts: 0, providers: 0, routingImported: false, notes: [] } }),
    catalogList: async () => ({ ok: true, data: { entries: [], source: "anonymous" } }),
    customEndpointsList: async () => ({ ok: true, data: [] }),
    customEndpointsUpsert: async () => ({ ok: true, data: undefined }),
    customEndpointsRemove: async () => ({ ok: true, data: undefined }),
    customEndpointsSaveKey: async () => ({ ok: true, data: undefined }),
    minimize: () => {},
    maximize: () => {},
    close: () => {},
    onServerStatus: () => () => {},
    isElectron: true,
    platform: "linux",
  };
}

export function stubCairn(overrides: Partial<CairnAPI> = {}): void {
  (globalThis as { window: Window }).window.cairn = { ...defaultCairn(), ...overrides };
}
