import type { Result, OverviewSummary, AccountView, ProviderRow, ProxyStatus, RoutingState, RoutingApp, Chain, AppPresence, CliResult, HomePlugins, UsageSnapshot, ImportableApp, ImportSummary, CatalogResult, AppSummary, PluginConfigSchema } from "./domain.js";
export interface CairnAPI {
  getConfig(name: string, key: string): Promise<Result<unknown>>;
  setConfig(name: string, key: string, value: unknown): Promise<Result<void>>;
  overviewSummary(): Promise<Result<OverviewSummary>>;
  accountsList(provider: string): Promise<Result<AccountView[]>>;
  accountsEnable(provider: string, id: string, on: boolean): Promise<Result<void>>;
  accountsRemove(provider: string, id: string): Promise<Result<void>>;
  accountsRefreshQuota(provider: string): Promise<Result<AccountView[]>>;
  providersList(): Promise<Result<ProviderRow[]>>;
  providersSetActive(id: string): Promise<Result<void>>;
  providersSetExposure(id: string, app: "cc" | "oc", on: boolean): Promise<Result<void>>;
  routingApps(): Promise<Result<RoutingApp[]>>;
  routingGet(app: string): Promise<Result<RoutingState>>;
  routingSetChain(app: string, slot: string, chain: Chain): Promise<Result<{ warnings: string[] }>>;
  proxyStatus(): Promise<Result<ProxyStatus>>;
  proxyStart(): Promise<Result<void>>;
  proxyStop(): Promise<Result<void>>;
  appsDetect(): Promise<Result<AppPresence>>;
  appsInstallCli(app: "claude" | "opencode"): Promise<Result<CliResult>>;
  appsInit(app: "claude" | "opencode"): Promise<Result<CliResult>>;
  appsUninstallCli(app: "claude" | "opencode", wipeData: boolean): Promise<Result<CliResult>>;
  appsSummary(app: "claude" | "opencode"): Promise<Result<AppSummary>>;
  pluginsList(): Promise<Result<HomePlugins[]>>;
  pluginsInstall(home: string, name: string, url: string): Promise<Result<void>>;
  pluginsSetEnabled(home: string, name: string, on: boolean): Promise<Result<void>>;
  pluginsDowngrade(home: string, name: string, hash: string): Promise<Result<void>>;
  pluginsUninstall(home: string, name: string): Promise<Result<void>>;
  configSchemas(home: string): Promise<Result<PluginConfigSchema[]>>;
  configWrite(home: string, plugin: string, key: string, value: unknown): Promise<Result<void>>;
  usageSnapshot(): Promise<Result<UsageSnapshot>>;
  importApps(): Promise<Result<ImportableApp[]>>;
  importRun(app: string): Promise<Result<ImportSummary>>;
  catalogList(): Promise<Result<CatalogResult>>;
  minimize(): void;
  maximize(): void;
  close(): void;
  onServerStatus(listener: (status: ProxyStatus) => void): () => void;
  isElectron: true;
  platform: NodeJS.Platform;
}
