import type { Result, OverviewSummary, AccountView, ProviderRow, ProxyStatus, ProxyView, RoutingState, RoutingApp, Chain, AppPresence, HostApp, AppConnection, RepoMeta, CliResult, HomePlugins, HomeLibraries, HomePluginData, AppStorage, AppStorageResult, AppPathNames, PluginVersion, UsageSnapshot, ImportableApp, ImportSummary, ImportPreview, ImportSelection, CatalogResult, MarketplaceSource, AppSummary, PluginConfigSchema, PluginScreen, ScreenData, InvokeResult, PluginSettingsSection, CustomEndpoint, CustomEndpointView, InstallManyResult, DownloadProgress, BusEvent, EngineView, LoginBegin, LoginComplete, GithubStatus, ActivityRecord, ActivityQuery, ActivityStats, FieldSpec, UpdateSummary, Job, JobKind } from "./domain.js";
export interface CairnAPI {
  getConfig(name: string, key: string): Promise<Result<unknown>>;
  setConfig(name: string, key: string, value: unknown): Promise<Result<void>>;
  overviewSummary(): Promise<Result<OverviewSummary>>;
  accountsList(provider: string): Promise<Result<AccountView[]>>;
  accountsEnable(provider: string, id: string, on: boolean): Promise<Result<void>>;
  accountsRemove(provider: string, id: string): Promise<Result<void>>;
  accountsRefreshQuota(provider: string): Promise<Result<AccountView[]>>;
  accountsLoginBegin(provider: string): Promise<Result<LoginBegin>>;
  accountsLoginComplete(provider: string, input: string): Promise<Result<LoginComplete>>;
  accountsLoginCancel(provider: string): Promise<Result<void>>;
  providersList(): Promise<Result<ProviderRow[]>>;
  providersSetEnabled(id: string, on: boolean): Promise<Result<void>>;
  providersSetExposure(id: string, app: string, on: boolean): Promise<Result<void>>;
  routingApps(): Promise<Result<RoutingApp[]>>;
  routingGet(app: string): Promise<Result<RoutingState>>;
  routingSetChain(app: string, slot: string, chain: Chain): Promise<Result<{ warnings: string[] }>>;
  proxyStatus(): Promise<Result<ProxyStatus>>;
  proxyStart(): Promise<Result<void>>;
  proxyStop(): Promise<Result<void>>;
  proxiesList(): Promise<Result<ProxyView[]>>;
  proxiesSetEnabled(name: string, on: boolean): Promise<Result<void>>;
  appsDetect(): Promise<Result<AppPresence>>;
  appsList(): Promise<Result<HostApp[]>>;
  jobsList(): Promise<Result<Job[]>>;
  jobsEnqueue(kind: JobKind, plugin: string, url: string, home: string): Promise<Result<Job>>;
  jobsCancel(id: string): Promise<Result<boolean>>;
  jobsClearFinished(): Promise<Result<void>>;
  appsInstallCli(app: string): Promise<Result<CliResult>>;
  appsUninstallCli(app: string, wipeData: boolean): Promise<Result<CliResult>>;
  appsSummary(app: string): Promise<Result<AppSummary>>;
  appsConnection(app: string): Promise<Result<AppConnection>>;
  appsInstallLoader(app: string): Promise<Result<void>>;
  appStorageGet(app: string): Promise<Result<AppStorage>>;
  appStorageSet(app: string, names: AppPathNames): Promise<Result<AppStorageResult>>;
  repoMeta(url: string): Promise<Result<RepoMeta>>;
  repoMetaCached(url: string): Promise<Result<RepoMeta | null>>;
  pluginsList(): Promise<Result<HomePlugins[]>>;
  pluginsListCached(): Promise<Result<HomePlugins[]>>;
  librariesList(): Promise<Result<HomeLibraries[]>>;
  librariesRemove(home: string, specifier: string): Promise<Result<void>>;
  pluginVersions(name: string): Promise<Result<Record<string, PluginVersion>>>;
  pluginVersionsAll(): Promise<Result<Record<string, Record<string, PluginVersion>>>>;
  pluginVersionsCached(): Promise<Result<Record<string, Record<string, PluginVersion>>>>;
  enginesList(): Promise<Result<EngineView[]>>;
  enginesEnsure(capability: string): Promise<Result<void>>;
  pluginsInstall(home: string, name: string, url: string, progressId?: number): Promise<Result<void>>;
  pluginsRemoveEverywhere(name: string): Promise<Result<InstallManyResult>>;
  pluginsSetEnabled(home: string, name: string, on: boolean): Promise<Result<void>>;
  pluginsSetAutoUpdate(home: string, name: string, on: boolean): Promise<Result<void>>;
  pluginsSetChannel(home: string, name: string, channel: "inherit" | "stable" | "experimental"): Promise<Result<void>>;
  pluginsDowngrade(home: string, name: string, hash: string): Promise<Result<void>>;
  pluginsUninstall(home: string, name: string): Promise<Result<void>>;
  pluginsData(name: string): Promise<Result<HomePluginData[]>>;
  pluginsRemoveData(home: string, paths: string[]): Promise<Result<string[]>>;
  configSchemas(home: string): Promise<Result<PluginConfigSchema[]>>;
  settingsSections(opts?: { wait?: boolean }): Promise<Result<PluginSettingsSection[]>>;
  configWrite(home: string, plugin: string, key: string, value: unknown): Promise<Result<void>>;
  configAction(home: string, plugin: string, actionId: string): Promise<Result<{ stdout: string; stderr: string }>>;
  screensList(opts?: { wait?: boolean }): Promise<Result<PluginScreen[]>>;
  screenData(plugin: string, screenId: string, home: string): Promise<Result<ScreenData>>;
  screenInvoke(plugin: string, screenId: string, actionId: string, home: string, args: Record<string, unknown>): Promise<Result<InvokeResult>>;
  busDrain(): Promise<Result<BusEvent[]>>;
  activityRead(query: ActivityQuery): Promise<Result<{ records: ActivityRecord[]; nextCursor?: string }>>;
  activityStats(): Promise<Result<ActivityStats>>;
  updatesCheck(homeId: string): Promise<Result<{ checkedAt: string; available: string[] }>>;
  updatesOne(homeId: string, name: string): Promise<Result<UpdateSummary>>;
  updatesAll(homeId: string): Promise<Result<UpdateSummary>>;
  globalSettingsRead(): Promise<Result<{ defaults: Record<string, unknown>; fields: FieldSpec[]; current: Record<string, unknown> }>>;
  usageSnapshot(): Promise<Result<UsageSnapshot>>;
  importApps(): Promise<Result<ImportableApp[]>>;
  importPreview(app: string): Promise<Result<ImportPreview>>;
  importRun(app: string, selection?: ImportSelection): Promise<Result<ImportSummary>>;
  catalogList(): Promise<Result<CatalogResult>>;
  catalogListCached(): Promise<Result<CatalogResult | null>>;
  githubStatus(): Promise<Result<GithubStatus>>;
  githubAddAccount(token: string, star: boolean): Promise<Result<{ login: string }>>;
  githubSwitchAccount(login: string): Promise<Result<void>>;
  githubRemoveAccount(login: string): Promise<Result<void>>;
  githubConnectGhCli(star: boolean): Promise<Result<{ login: string }>>;
  githubSetStar(url: string, starred: boolean): Promise<Result<void>>;
  githubStarCairn(): Promise<Result<void>>;
  githubDeviceStart(): Promise<Result<{ userCode: string; verificationUri: string; intervalSeconds: number }>>;
  githubDevicePoll(star: boolean): Promise<Result<{ status: string; login?: string; message?: string; intervalSeconds?: number }>>;
  favoritesList(): Promise<Result<string[]>>;
  favoritesToggle(name: string): Promise<Result<string[]>>;
  marketplaceSourcesList(): Promise<Result<MarketplaceSource[]>>;
  // Saved as one list because its ORDER is which marketplace wins a name both publish.
  marketplaceSourcesSave(sources: MarketplaceSource[]): Promise<Result<MarketplaceSource[]>>;
  customEndpointsList(): Promise<Result<CustomEndpointView[]>>;
  // The wire formats the provider plugin can translate, asked of it rather than restated here.
  customEndpointsFormats(): Promise<Result<string[]>>;
  customEndpointsUpsert(endpoint: CustomEndpoint): Promise<Result<void>>;
  customEndpointsRemove(id: string): Promise<Result<void>>;
  customEndpointsSaveKey(endpointId: string, key: string): Promise<Result<void>>;
  minimize(): void;
  maximize(): void;
  close(): void;
  onServerStatus(listener: (status: ProxyStatus) => void): () => void;
  onDownloadProgress(listener: (progress: DownloadProgress) => void): () => void;
  onActivityEvent(listener: (record: ActivityRecord) => void): () => void;
  onJobEvent(listener: (job: Job) => void): () => void;
  isElectron: true;
  platform: NodeJS.Platform;
}

