import type { Result, OverviewSummary, AccountView, ProviderRow, ProxyStatus, ProxyView, RoutingState, RoutingApp, Chain, AppPresence, HostApp, AppConnection, RepoMeta, CliResult, HomePlugins, PluginVersion, UsageSnapshot, ImportableApp, ImportSummary, ImportPreview, ImportSelection, CatalogResult, AppSummary, PluginConfigSchema, CustomEndpoint, CustomEndpointView, InstallManyResult, SyncStatus, ConfigHomeView, ConfigDiffRow, ProfileSwitchResult, BusEvent, EngineView, LoginBegin, LoginComplete } from "./domain.js";
export interface CairnAPI {
  getConfig(name: string, key: string): Promise<Result<unknown>>;
  setConfig(name: string, key: string, value: unknown): Promise<Result<void>>;
  overviewSummary(): Promise<Result<OverviewSummary>>;
  accountsList(provider: string): Promise<Result<AccountView[]>>;
  accountsEnable(provider: string, id: string, on: boolean): Promise<Result<void>>;
  accountsRemove(provider: string, id: string): Promise<Result<void>>;
  accountsRefreshQuota(provider: string): Promise<Result<AccountView[]>>;
  accountsLoginBegin(provider: string): Promise<Result<LoginBegin>>;
  accountsLoginComplete(provider: string, input: string): Promise<Result<LoginComplete>>;
  accountsLoginCancel(provider: string): Promise<Result<void>>;
  providersList(): Promise<Result<ProviderRow[]>>;
  providersSetActive(id: string): Promise<Result<void>>;
  providersSetExposure(id: string, app: string, on: boolean): Promise<Result<void>>;
  routingApps(): Promise<Result<RoutingApp[]>>;
  routingGet(app: string): Promise<Result<RoutingState>>;
  routingSetChain(app: string, slot: string, chain: Chain): Promise<Result<{ warnings: string[] }>>;
  proxyStatus(): Promise<Result<ProxyStatus>>;
  proxyStart(): Promise<Result<void>>;
  proxyStop(): Promise<Result<void>>;
  proxiesList(): Promise<Result<ProxyView[]>>;
  proxiesSetEnabled(name: string, on: boolean): Promise<Result<void>>;
  appsDetect(): Promise<Result<AppPresence>>;
  appsList(): Promise<Result<HostApp[]>>;
  appsInstallCli(app: string): Promise<Result<CliResult>>;
  appsInit(app: string): Promise<Result<CliResult>>;
  appsUninstallCli(app: string, wipeData: boolean): Promise<Result<CliResult>>;
  appsSummary(app: string): Promise<Result<AppSummary>>;
  appsConnection(app: string): Promise<Result<AppConnection>>;
  appsInstallLoader(app: string): Promise<Result<void>>;
  repoMeta(url: string): Promise<Result<RepoMeta>>;
  pluginsList(): Promise<Result<HomePlugins[]>>;
  pluginVersions(name: string): Promise<Result<Record<string, PluginVersion>>>;
  pluginVersionsAll(): Promise<Result<Record<string, Record<string, PluginVersion>>>>;
  enginesList(): Promise<Result<EngineView[]>>;
  enginesEnsure(capability: string): Promise<Result<void>>;
  pluginsInstall(home: string, name: string, url: string): Promise<Result<void>>;
  pluginsInstallMany(name: string, url: string, homeIds: string[]): Promise<Result<InstallManyResult>>;
  pluginsRemoveEverywhere(name: string): Promise<Result<InstallManyResult>>;
  pluginsSetEnabled(home: string, name: string, on: boolean): Promise<Result<void>>;
  pluginsDowngrade(home: string, name: string, hash: string): Promise<Result<void>>;
  pluginsUninstall(home: string, name: string): Promise<Result<void>>;
  configSchemas(home: string): Promise<Result<PluginConfigSchema[]>>;
  configWrite(home: string, plugin: string, key: string, value: unknown): Promise<Result<void>>;
  configAction(home: string, plugin: string, actionId: string): Promise<Result<{ stdout: string; stderr: string }>>;
  syncStatus(): Promise<Result<SyncStatus>>;
  syncRun(): Promise<Result<void>>;
  syncSetConfig(key: string, value: unknown): Promise<Result<void>>;
  ledgerHomes(): Promise<Result<ConfigHomeView[]>>;
  ledgerCommit(home: string, reason: string): Promise<Result<boolean>>;
  ledgerRestore(home: string, ref: string): Promise<Result<number>>;
  ledgerDiffRefs(home: string, refA: string, refB: string): Promise<Result<ConfigDiffRow[]>>;
  ledgerProfileCreate(home: string, name: string): Promise<Result<void>>;
  ledgerProfileSwitch(home: string, name: string): Promise<Result<ProfileSwitchResult>>;
  busDrain(): Promise<Result<BusEvent[]>>;
  usageSnapshot(): Promise<Result<UsageSnapshot>>;
  importApps(): Promise<Result<ImportableApp[]>>;
  importPreview(app: string): Promise<Result<ImportPreview>>;
  importRun(app: string, selection?: ImportSelection): Promise<Result<ImportSummary>>;
  catalogList(): Promise<Result<CatalogResult>>;
  customEndpointsList(): Promise<Result<CustomEndpointView[]>>;
  customEndpointsUpsert(endpoint: CustomEndpoint): Promise<Result<void>>;
  customEndpointsRemove(id: string): Promise<Result<void>>;
  customEndpointsSaveKey(endpointId: string, key: string): Promise<Result<void>>;
  minimize(): void;
  maximize(): void;
  close(): void;
  onServerStatus(listener: (status: ProxyStatus) => void): () => void;
  isElectron: true;
  platform: NodeJS.Platform;
}
