name: Promote to Experimental
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
      - '!v*'
permissions:
  contents: write
jobs:
  promote:
    uses: intisy/workflows/.github/workflows/merge.yml@main
    with:
      source: ${{ github.sha }}
      target: experimental
